### ISSUE TITLE
How it works Page

### ISSUE THREAD

**Issue by Josephrp** [Alonski/CoinPanion#11]
a page explaining how CoinPanion works.

**Comment by Josephrp** [comment]
Text should follow color codes and rhetoric model!

**Comment by Josephrp** [comment]
WE ALL HAVE SPECIAL PEOPLE THAT MERIT OUR ATTENTION. THESE PEOPLE ARE OUR GRANDMAS, COLLEGUES, NEIHBORS, OR COINPANIONS.

REGULARLY PAY YOUR COINPANIONS. CREDIT CONTRACTS BETWEEN YOU AND THOSE THAT DESERVE IT. 

WE USE THE ETH PUBLIC CHAIN TO HELP YOU REACH MILLIONS OF POTENTIAL BENEFICIARIES WORLDWIDE.  STATUS.IM GIVES A MOBILE HOME TO YOUR BANK ACCOUNT. 

SIMPLY, CONNECT, FIND, SEND, AND ENJOY!

**Comment by Josephrp** [comment]
BLUE WORDS:

1. Deserve
2. Beneficiaries
3. Enjoy

**Comment by Alonski** [comment]
Can't this be incorporated into the About Page #1

**Comment by rhlsthrm** [comment]
I agree, this content should be in the about page.

**Comment by Josephrp** [comment]
I'm happy to close this issue as it has been clarified.
