### ISSUE TITLE
Gamify!

### ISSUE THREAD

**Issue by Josephrp** [Alonski/CoinPanion#12]
Gamification is common better practice when it comes to user engagement. Better practice in gamification includes - diversity, warmth, easy to win difficult to master. 

Let's instead of counters - which are transparent and intrussive - let's give coinpanions badges?

Badge ideas:

Hero Badge : 10+ subscribers
Tropical Badge : location = tropics
Nordic Badge : location = north east from France
Cesare Badge : Location = Western Europe
American Badge = South American
Indian Badge = North America
Raja = India
Kim Jun Ung = Rest of Asia
Picachu = Pacific Islands
Seed = send 3+ subscriptions
Root = send 6+ Subscriptions
tree = send 9+ Subscriptions

**Comment by Alonski** [comment]
This could be a good idea.
I think this should be left for the end once everything else works. 
Then we can go about implementing this.

**Comment by rhlsthrm** [comment]
I agree, it's a great idea but let's leave it until everything else works.

**Comment by Josephrp** [comment]
also agree :-)

**Comment by rhlsthrm** [comment]
Let's close until after the hackathon?
