### ISSUE TITLE
Rhetoric and some tricks

### ISSUE THREAD

**Issue by Josephrp** [Alonski/CoinPanion#13]
(I'm not sales and frankly i don't understand it but:) 
Most folks in sales agree on this : 

Using capital letters
write key words in blue,
write "positive" words in green,
Red is danger

Rhetoric : simple format : once upon a time.... for reasons, graber, arguments, regraber call to action.

keeping it super short.

**Comment by Alonski** [comment]
Are you suggesting we follow a certain coloring format for the whole site?
The UI framework we are using follows the Red: Danger, Blue: Info, Green: Positive convention.
What do you mean in your Rhetoric?

**Comment by rhlsthrm** [comment]
Capital letters as in all caps?

**Comment by Josephrp** [comment]
yeah :-) great that the UI Framework is following the conventions! Also accessibility... very important - i want a blind person to be using this daily... in three years, but ... did you know 82% of blind people use internet every day? 33% are illiterate in france.

**Comment by Alonski** [comment]
I agree that accessibility is important but it is outside the scope of the hackathon.
