### ISSUE TITLE
Functionality : share on social media

### ISSUE THREAD

**Issue by Josephrp** [Alonski/CoinPanion#15]
I do think such a functionality should be interesting : 

- just subscribed : share
- completed profile : share
- subscriptions : share

**Comment by Alonski** [comment]
This could actually be interesting and is relatively simple to  implement.
Could have for Facebook, Twitter, Email... Any more?

Need to decide exactly for which transactions and how to structure the messages

**Comment by rhlsthrm** [comment]
I say for the MVP we should stick to Twitter share and Facebook share through their share dialog API (which is easy to implement). We shouldn't mess with Facebook linking, API keys and all that stuff.

**Comment by Alonski** [comment]
@rhlsthrm Makes sense. Keep it simple but show the basic idea

**Comment by Josephrp** [comment]
The general idea is to allow coinpanions to share their subscribe
"requests" and let folks know they are ready to receive :-)

**Comment by rhlsthrm** [comment]
We probably should punt this to after the hackathon.
