### ISSUE TITLE
Create New Profile

### ISSUE THREAD

**Issue by Alonski** [Alonski/CoinPanion#2]
Allow a user to create their profile:
Authentication can be done completely with the blockchain using Ethereum Address:
MetaMask, Mist, Status

Features:
- Name
- Picture
- Description (Markdown)
- Tags/Category (for search and filtration)

We can also just make the whole page Markdown for the MVP

**Comment by rhlsthrm** [comment]
Pictures? I think one profile picture is enough for the MVP. We should keep the profile as simple as possible.

**Comment by Alonski** [comment]
I meant this as the main page for each user. The page where other users go to subscribe to you.

**Comment by rhlsthrm** [comment]
OK I see. We should also define what "More" is. I think this is one of the more important pages in the MVP so let's define what should be on it.

**Comment by Alonski** [comment]
Yea I put this here so we can start discussion 😄

**Comment by Josephrp** [comment]
My 2 cents :KEEP IT ULTRA SIMPLE... and i agree with Alon (i agree with everybody :-) )
Picture, Page Name (displayed), Full Name (used for signature! NOT DISPLAYED), OAUTH, Pictures with an s... why not limit to 3? One entry maybe where the coinpanions gives a rough idea of what range subscriptions they need (interger scale from 1 - 8999 <-- fiscal limit one markdown text box, that's it.

PS... sorry for saying ultra simple, then proposing more functionality... i realise it haha..

**Comment by Josephrp** [comment]
oh sorry... just realised... we won't be displaying in Euros!! scale is decimal from 1 coinpanion (mili eth) to four hundred and twenty thousand coinpanions (420.000) ...

**Comment by rhlsthrm** [comment]
This will also need to insert users into the database.

**Comment by Alonski** [comment]
@rhlsthrm Yea this will connect Eth Addresses with Names, Emails etc for each User

**Comment by imbaniac** [comment]
@Alonski @rhlsthrm @Josephrp 
Full user profile schema:
- id
- first_name
- last_name
- email
- eth_address
- photo_url
- biography
- category
- content (for titles - Sam Harris is creating The Waking Up Podcast) - optional

**Comment by Alonski** [comment]
@imbaniac Looks great!

**Comment by rhlsthrm** [comment]
@imbaniac I propose we merge id and eth_address and use eth_address as the key. The eth_address should not ever change per user, correct?

**Comment by imbaniac** [comment]
@rhlsthrm In fact, I think, eth address can be changed. IE, user lost access to wallet or decided to use another address and delete this

**Comment by rhlsthrm** [comment]
@imbaniac okay got it, so then maybe it makes sense to keep a unique identifier in our own database.

**Comment by Josephrp** [comment]
I would most likely reccommend changing inbound addresses every inbound
transaction :-) feature for status? Was going to put that into How it works
page - unless Any one objecto ?

**Comment by Josephrp** [comment]
XD autocorrect ! Will édit this from home!

**Comment by rhlsthrm** [comment]
My latest pull request ( #33 ) implements the Edit Profile page. Please review.
