### ISSUE TITLE
Figure out how to structure project

### ISSUE THREAD

**Issue by rhlsthrm** [Alonski/CoinPanion#28]
I think we should nest components by functionality and how they will be used, similar to what this article describes: https://medium.com/@alexmngn/how-to-better-organize-your-react-applications-2fd3ea1920f1

We can have top level components and nest components within our "scenes". What do you guys think?

**Comment by rhlsthrm** [comment]
My latest PR has a first-pass implementation of this structure.

**Comment by imbaniac** [comment]
It's a good idea for enterprise apps with a ton of components, but for us, it'll be overcomplication.
We just don't need to have standalone modules and creating own actions, reducers, and components in each folder will be crazy.
Let's follow regular:
- actions
- components
- containers
- reducers
- utils

Still, we can borrow some ideas from the architecture

**Comment by rhlsthrm** [comment]
So far I've found it easier working this way but if you guys are used to the traditional methods I'm fine with that.

**Comment by imbaniac** [comment]
It's easier while we haven't added redux. [This post](https://medium.com/@alexmngn/how-to-use-redux-on-highly-scalable-javascript-applications-4e4b8cb5ef38) describes a few bad practices and very complicated nested structure.

**Comment by rhlsthrm** [comment]
OK let's refactor on top of the code I checked in then.
