### ISSUE TITLE
Coinpanion "Pro" / Coinpanion "Free"

### ISSUE THREAD

**Issue by Josephrp** [Alonski/CoinPanion#36]
There's a significant difference in user requirements (intensity of transactions, branding, support) for proffessionals that offer a service  proffessionally and those that are simply sending money to another user (friends, familly, that sort of thing).

Could be interesting to plan a feature for this?

**Comment by Alonski** [comment]
I think for the MVP there is no need for this.
Also in the future I am not sure that we want to differentiate between users at the start to facilitate growth

**Comment by Josephrp** [comment]
correct. add to pitch-deck roadmap?

**Comment by Alonski** [comment]
Hmm we could add this to the roadmap sure
