### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Alonski** [Alonski/CoinPanion#5]
My Profile:
- My username (ether address)
- Supporting: Username (ether address) of users that I am supporting

Possibly add suggestions of users to support

**Comment by Josephrp** [comment]
disagree!!!

Home page should always be signup - not sign in! Why? because status is not democratised yet, so 9/10 times the person should be able to create a profile for her beneficiary _in situ_ by signing her up, then sign in, then send. simple.

**Comment by Josephrp** [comment]
Propose : call this the profile page.

**Comment by Alonski** [comment]
Why would a user need to sign up?
We aren't going to be creating Ether Addresses for anyone.
People will use their own Ether Addresses.

We technically could create a brand new Ether Address for each user and then have people sign up with the common Username/Password combo but I think that this isn't needed and could actually turn off current AltCoin users

We need to keep this as simple as possible for the MVP and simple means no username and no password

**Comment by rhlsthrm** [comment]
So how will they sign in? Just by typing in their Ether address?

**Comment by Alonski** [comment]
With Metamask, Mist, Status. You have an Ethereum address just by using them if I am not wrong

**Comment by imbaniac** [comment]
We can сombine homepage and dashboard. Will be easier to implement

**Comment by imbaniac** [comment]
And I agree that we don't need sign up. We can let people sign in only with their eth address. Let's follow KISS methodology

**Comment by rhlsthrm** [comment]
"Homepage" will either be the dashboard that shows your personal profile/stats (how many supporters/supported) or else the explore page.

**Comment by Alonski** [comment]
I think it could be a combination of both but maybe for the MVP we should really keep it simple and only show the Explore Page as the Home Page

**Comment by rhlsthrm** [comment]
Agreed @Alonski we will not have a separate page for Home Page.

**Comment by imbaniac** [comment]
If we won't have HomePage we should show people to whom they are subscribed elsewhere (ie navbar)
